version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw
    env_file:
      - .docker/db.env
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/sql/:/docker-entrypoint-initdb.d/
  web:
    image: nginx

    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public/:/var/www/html/public
    depends_on:
      - db
      - php-fpm
    ports:
      - "80:80"
  php-fpm:
    image: php:8.2-fpm
    env_file:
      - .docker/db.env
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
#      - ./public/:/var/www/html
#      - ./app/:/var/www/app
#      - ./vendor:/var/www/vendor
    ports:
      - ":9000"