version: '3'
services:
  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw
    env_file:
      - .docker/db.env
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/sql/:/docker-entrypoint-initdb.d/
    networks:
      bridge:
        aliases:
          - "db.local"
  web:
    image: nginx
    volumes:
      # nginx site config
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # public root
      - ./public/:/var/www/html/public
    depends_on:
      - mysql-db
      - php-fpm
    ports:
      - "80:80"
    networks:
      bridge:
        aliases:
          - "web.local"
  php-fpm:
    build: .docker/php/.
    environment:
      MYSQL_HOST: db.local
    env_file:
      - .docker/db.env
    depends_on:
      - mysql-db
    volumes:
      - .:/var/www/html/
    ports:
      - ":9000"
    networks:
      bridge:
        aliases:
          - "php-fpm.local"
networks:
  bridge: